import "../globals.css";
import RevalidateComponent from "@/components/RevalidateComponent";
export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by Next + Sanity",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <RevalidateComponent />
      </body>
    </html>
  );
}
